created user posting functionality
madilkhan002/Weather-Man pull request #8
Opened 2024-07-09 10:04 UTC by madilkhan002

2024-07-09 13:49 UTC, somantalha requested changes

2024-07-09 13:49 UTC, somantalha commented on olx/mobile/urls.py
> +app_name = "mobile"
Why we need to add `app_name` here. Can we avoid this ?

2024-07-09 13:49 UTC, somantalha commented on olx/mobile/utils.py
> +    POSTING_PER_PAGE = 1
Can we store these constants in `constants.py`?

2024-07-09 13:49 UTC, somantalha commented on olx/mobile/views.py
> +)
Can we use `absolute imports`.

2024-07-09 13:49 UTC, somantalha commented on olx/mobile/views.py
> +    authenticate_user(request)
Can we use `@login_required` here ?

2024-07-09 13:49 UTC, somantalha commented on olx/mobile/views.py
> +    current_user_posting = get_user_posting(request)
Can we use query here directly instead of invoking a method just for this?

2024-07-09 13:49 UTC, somantalha commented on olx/mobile/views.py
> +    filtered_user_posting = perform_filtering(request, current_user_posting)
Can we use Django filters for this ?

2024-07-09 13:49 UTC, somantalha commented on olx/mobile/utils.py
> +    return postings, paginator, current_page
Can we make a dict of these values `postings, paginator, current_page` and return it ?

2024-07-10 08:08 UTC, UsmanAli99 requested changes

2024-07-10 08:08 UTC, UsmanAli99 commented on olx/mobile/urls.py
> +    path("posting/", views.user_posting, name="user_posting"),
path("", views.user_mobile_listing, name="mobiles"),

2024-07-10 08:08 UTC, UsmanAli99 commented on olx/mobile/utils.py
> +    current_page = request.GET.get('page') or DEFAULT_PAGE
Create separate method for this

2024-07-10 10:28 UTC, merged